### ISSUE TITLE
BUG: Region exporting to itself through Commodity trade route

### ISSUE THREAD

**Issue by Drowsle** [transition-zero/tz-osemosys#125]
### Checklist

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of tz-osemosys.

- [ ] I have confirmed this bug exists on the main branch of tz-osemosys.

### Reproducible Example

```
# My Example Yaml-Loading Model

# alias data
# custom defined cross-references
ELEC-DAILY-PROFILE:
  s1-h1: 0.05 # 0 - 4
  s1-h2: 0.10 # 4 - 8
  s1-h3: 0.20 # 8 - 12
  s1-h4: 0.20 # 12 - 16
  s1-h5: 0.30 # 16 - 20
  s1-h6: 0.15 # 20 - 24

# Model Nameplate
id: my-model
long_name: "Example Model - California+Texas interconnection"
description: >
  California+Texas interconnection.
  An example model to show how we can create an OSeMOSYS model from json/yaml.
  In this model, California and Texas have comparative advantages in solar and wind respectively,
  and start with very little interconnection.
  Both states can import gas and coal from pacific and atlantic markets respectively.
  Texas can also extract gas and coal, but their ability to do so diminishes with time.
  The electricity system is constrained to acheive net zero by the end of the model period.


# REGIONS
regions:
  - id: US-CA
    long_name: California
    description: "The US state of California"

  - id: US-TX
    long_name: Texas
    description: "The US state of Texas"

  - id: ATLANTIC-MARKET
    long_name: atlantic market
    description: a node representing atlantic import markets

  - id: PACIFIC-MARKET
    long_name: pacific market
    description: a node representing pacific import markets

# TIME DEFINTIONS
time_definition:
  id: 2022_2040_6yrpart_12daypart
  years: "range(2022,2041)"
  daily_time_brackets: [1,2,3,4,5,6]
  seasons: [1]
  timeslices: ["s1-h1", "s1-h2", "s1-h3", "s1-h4", "s1-h5", "s1-h6"]
  timeslice_in_timebracket: {"s1-h1": 1,
                             "s1-h2": 2,
                             "s1-h3": 3,
                             "s1-h4": 4,
                             "s1-h5": 5,
                             "s1-h6": 6}
  timeslice_in_season: {"s1-h1": 1, "s1-h2": 1, "s1-h3": 1, "s1-h4": 1, "s1-h5": 1, "s1-h6": 1}

# FINANCIALS
depreciation_method: "straight-line"
discount_rate: 0.05

# COMMODITIES
commodities:
  - id: ELEC
    long_name: Electricity
    description: Electricity
    include_in_joint_reserve_margin: true
    include_in_joint_renewable_target: true
    demand_annual: # EJ/yr
      US-CA: "{y:(0.7*1.1**(y-2022)) for y in ${time_definition.years}}"
      US-TX: "{y:(1.73*1.1**(y-2022)) for y in ${time_definition.years}}"
      ATLANTIC-MARKET: "{y:1 for y in ${time_definition.years}}"
    demand_profile:
      "*":                           # region
        "*": "${ELEC-DAILY-PROFILE}"    # year: timeslice

# TRADE ROUTES
trade:
  - id: Electricity transmission
    commodity: ELEC
    trade_routes:
      US-CA: 
        US-TX:
          "*": true
      US-CA: 
        PACIFIC-MARKET:
          "*": true
      US-TX: 
        ATLANTIC-MARKET:
          "*": true

    capex: 1
    operational_life: 100
    construct_region_pairs: true


# IMPACTS
impacts:
  - id: CO2
    long_name: equivalent carbon dioxide emissions
    description: equivalent carbon dioxide emissions
    penalty: # mn$/mntonne
      US-CA: 20.
      US-TX: 10.
    constraint_annual: "{y:225*((2041-y)/(2041-2022)) for y in ${time_definition.years}}"

# RENEWABLE TARGETS
renewable_production_target:
  US-CA: "{y:0.1*((2041-y)/(2041-2022))+0.4 for y in ${time_definition.years}}"
  US-TX: "{y:0.1*((2041-y)/(2041-2022))+0.2 for y in ${time_definition.years}}"

# RESERVE MARGINS
reserve_margin: 1.1

technologies:
  - id: SPV
    long_name: solar photovoltaic
    description: solar photovoltaic
    capacity_activity_unit_ratio: 30.41667
    capacity_one_tech_unit: null
    availability_factor: 1.
    capacity_factor: 1.
    operating_life: 25
    include_in_joint_reserve_margin: true
    include_in_joint_renewable_target: true
    # Not Implemented
    # include_regions: null
    # exclude_regions:
    #   - ATLANTIC-MARKET
    #   - PACIFIC-MARKET
    capex:
      "*": "{y:700 - 100*(max(${time_definition.years})-y)/(max(${time_definition.years}) - min(${time_definition.years})) for y in ${time_definition.years}}"
    opex_fixed: 10
    operating_modes:
      - id: GEN
        long_name: generation mode
        description: default generation mode
        emission_activity_ratio: {"CO2": 0.}
        input_activity_ratio: null
        output_activity_ratio:
          "*":            # all regions
            ELEC:
              "*":        # all years
                1.
        to_storage: null
        from_storage: null
        opex_variable: 0.
    residual_capacity: 
      US-CA:
        166.3
      US-TX:
        166.3
      ATLANTIC-MARKET:
        0
      PACIFIC-MARKET:
        0

    # CAPACITY
    capacity_gross_max: 500.
    capacity_gross_min: 0.
    # capacity_additional_max: 
    #   ATLANTIC-MARKET:
    #     0

    # To be implemented
    # additional_capacity_max_ceil: null
    # additional_capacity_max_floor: 5
    # additional_capacity_max_growth_rate: 0.1
    # additional_capacity_min_growth_rate: 0.


    # constraints - activity
    activity_annual_max: null
    activity_annual_min: null
    activity_total_max: null
    activity_total_min: null
```

### Issue Description

The reproductible example is based on the CAISO-ERCOT-IC example to which I have added the new trade_routes format introduced in version v0.0.8 . I have also added electricity demand in the ATLANTIC-MARKET while preventing electricity production in all regions except US-TX and US-CA. Therefore, ATLANTIC-MARKET should only import electricity from either US-TX or US-CA.

However, ATLANTIC-MARKET seems to be importing electricity from itself despite specifying in that the trade route from ATLANTIC-MARKET to itself is not open. Moreover, it imports electricity from PACIFIC-MARKET and US-CA despite having no direct connection with these regions and despite PACIFIC-MARKET having no electricity production technology. There is an indirect link through US-TX which is also the only region with a direct link to ATLANTIC-MARKET and the only region it doesn't import from. 

The code I used to plot the trades : 

```
from tz.osemosys import Model
import matplotlib.pyplot as plt
import numpy as np


model = Model.from_yaml("CAISO-ERCOT-IC main.yaml")

model.solve()

results = model.solution

Trades = results.Import.to_dataframe().div(3.6).reset_index().pivot_table(index = ['REGION', 'YEAR', 'TIMESLICE'], columns = ['_REGION'], values = 'Import', aggfunc = 'sum')
fig, ax = plt.subplots(len(Trades.index.levels[0]))
for i in range(len(Trades.index.levels[0])):
    region = Trades.index.levels[0][i]
    Trades.loc[region].plot.area(title = 'Imports to {}'.format(region), ax = ax[i], figsize = (10, 20), linewidth=0, stacked = True)
```
![results](https://github.com/transition-zero/tz-osemosys/assets/94905948/0de72e91-f893-4c93-b20a-67645e936987)

### Expected Behavior

ATLANTIC-MARKET shouldn't be able to import from himself and PACIFIC-MARKET shouldn't be able to export to it either. 

Even though the electricity is produced in US-CA, it should be labeled as coming from the region it is directly linked to, US-TX for instance.
